name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install tools
        uses: ok-nick/setup-aftman@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "v0.2.6"
          trust-check: false
      - name: Lint
        run: |
          selene ./src

  style:
    name: Styling
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          args: --check .
